# HIIIIIIIII

### Reshaping arrays

In [4]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3) # reshape to 2 rows and 3 columns
reshaped

array([[1, 2, 3],
       [4, 5, 6]])

### Universal Functions (ufunc)

#### Mathematical Operations

In [17]:
x = [0,1, 2 ,3 ]

In [21]:
x=np.arange(4)

In [23]:
print("x =",x)

x = [0 1 2 3]


In [27]:
print("x +5 =",x+5)

x +5 = [5 6 7 8]


In [29]:
print("x * 2 =",x*2)

x * 2 = [0 2 4 6]


In [31]:
print("x / 2 =",x/2)

x / 2 = [0.  0.5 1.  1.5]


In [33]:
print("x // 2 =",x//2) # its called as floor division

x // 2 = [0 0 1 1]


In [35]:
print("x**2 = ",x**2)

x**2 =  [0 1 4 9]


In [37]:
print("x^2 = ",x^2)

x^2 =  [2 3 0 1]


In [39]:
print(np.add(x,5)) 

[5 6 7 8]


In [41]:
# adding 'add' (functions) instead of "+" (operators), 
#has no effect on the outcome but its easy to mess up with operators cuz you might get lost with the amount of numbers involved

In [43]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [45]:
np.power(x,2)

array([0, 1, 4, 9], dtype=int32)

### Creating a 2D array

In [72]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Creating a identity matrix

In [75]:
arr2 = np.eye(3)
arr2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
arr1.ndim

2

In [93]:
print("arr1 x arr2 = \n\n",arr1*arr2) #element wise multiplcaion (cant use for matrice multiplication)

arr1 x arr2 = 

 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]


In [97]:
np.dot(arr1,arr2) # gives the tradition matrice multiplication 

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [99]:
arr1@arr2 # gives the tradition matrice multiplication 

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [101]:
x = np.array([-2, -1, 0, 1, 2])
abs(x) # Whats this?

array([2, 1, 0, 1, 2])

### Trigonometry

In [103]:
angle = np.pi/4 

In [120]:
print("cosine:",round(np.cos(angle),2))

cosine: 0.71


In [125]:
print("sin:", round(np.sin(angle),2))

sin: 0.71


In [151]:
y=np.pi
print("y =",y)

y = 3.141592653589793


In [157]:
round(y,2)

In [163]:
value = np.pi
formatted_value="{:.2f}".format(value)
print(formatted_value)

3.14


In [165]:
a=180

In [175]:
round(np.deg2rad(a),2)

In [177]:
b = np.pi/4

In [179]:
b

In [185]:
print("b =",np.rad2deg(np.pi/4))

b = 45.0


In [193]:
z = np.array([1,2,3])

In [209]:
np.power(z,3)

array([ 1,  8, 27], dtype=int32)

In [213]:
np.power(z,np.e)

array([ 1.        ,  6.58088599, 19.81299075])

In [215]:
data = np.array([10,20,30,40,50,])

In [217]:
print("minimum value is = ",np.min(data))

minimum value is =  10


In [219]:
print("maximum value is =",np.max(data))

maximum value is = 50


### multiple ways to calculate the mean

In [225]:
print("Total is = ",(T:= np.sum(data)))

Total is =  150


In [231]:
print("The mean is=",(T/len(data)))

The mean is= 30.0


In [235]:
print("The mean is=",(sum(data)/len(data)))

The mean is= 30.0


In [242]:
print("The mean is=",np.mean(data))

The mean is= 30.0


In [245]:
A = sum(data)
B=len(data)

In [247]:
print("The mean is =",A/B)

The mean is = 30.0


## lab

### Question 1

In [250]:
a = np.array([2,9,16,25])

In [256]:
print("Sqrt",np.sqrt(a))

Sqrt [1.41421356 3.         4.         5.        ]


In [262]:
print("square",np.square(a))

square [  4  81 256 625]


### Question 2

In [286]:
qt = np.array([0,np.pi/6,np.pi/4,np.pi/2])

In [288]:
print("sin =",np.sin(qt))
print("cos =",np.cos(qt))
print("tan =",np.tan(qt))

sin = [0.         0.5        0.70710678 1.        ]
cos = [1.00000000e+00 8.66025404e-01 7.07106781e-01 6.12323400e-17]
tan = [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.63312394e+16]


### Question 3

In [290]:
a = np.array([10,20,30,40])
p = print

In [304]:
p("sum",sum(a), "\nmean", np.mean(a), "\nmax",np.max(a))

sum 100 
mean 25.0 
max 40


### Comparison operators

In [317]:
r = np.array([1,2,3])
p = np.array([3,2,1])

In [314]:
print(np.equal(r,p))

[False  True False]


In [321]:
print(r==p)

[False  True False]
