#### Download pandas

In [3]:
pip install pandas 

Note: you may need to restart the kernel to use updated packages.


In [3]:
import pandas as pd
import numpy as np

#### Check the version of pandas

In [10]:
print(pd.__version__)

2.2.2


#### Identify current working directory

In [12]:
import os
print(os.getcwd())

C:\Users\CL3-6\Desktop


# Download the seattle2014.csv file 

### Using the raw link from github

In [33]:
df = pd.read_csv('https://raw.githubusercontent.com/amankharwal/Website-data/refs/heads/master/Seattle2014.csv')
df.head()

STATION                                STATION_NAME      DATE  \
0  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140101   
1  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140102   
2  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140103   
3  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140104   
4  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140105   

   PRCP  SNWD  SNOW  TMAX  TMIN  AWND  WDF2  WDF5  WSF2  WSF5  WT01  WT05  \
0     0     0     0    72    33    12   340   310    36    40 -9999 -9999   
1    41     0     0   106    61    32   190   200    94   116 -9999 -9999   
2    15     0     0    89    28    26    30    50    63    72     1 -9999   
3     0     0     0    78     6    27    40    40    45    58     1 -9999   
4     0     0     0    83    -5    37    10    10    67    76 -9999 -9999   

   WT02  WT03  
0 -9999 -9999  
1 -9999 -9999  
2 -9999 -9999  
3 -9999 -9999  
4 -9999 -9999

### Using the file name

In [27]:
df = pd.read_csv('Seattle2014.csv') # make sure your csv file is in your current working directory, check it using cwd
df.head()

STATION                                STATION_NAME      DATE  \
0  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140101   
1  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140102   
2  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140103   
3  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140104   
4  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140105   

   PRCP  SNWD  SNOW  TMAX  TMIN  AWND  WDF2  WDF5  WSF2  WSF5  WT01  WT05  \
0     0     0     0    72    33    12   340   310    36    40 -9999 -9999   
1    41     0     0   106    61    32   190   200    94   116 -9999 -9999   
2    15     0     0    89    28    26    30    50    63    72     1 -9999   
3     0     0     0    78     6    27    40    40    45    58     1 -9999   
4     0     0     0    83    -5    37    10    10    67    76 -9999 -9999   

   WT02  WT03  
0 -9999 -9999  
1 -9999 -9999  
2 -9999 -9999  
3 -9999 -9999  
4 -9999 -9999

In [42]:
# To print the first few rows of the csv file use : print(df.head())

### Convert a column to numpy array (inorder to do mathematical operations on the column)

In [211]:
rainfall = pd.read_csv('Seattle2014.csv')['PRCP'].values 
inches = rainfall/254.0 
inches.shape

#The .values attribute is used to convert a Pandas Series (which is a one-dimensional labeled array) into a NumPy array. 
#This allows you to perform NumPy operations on the data, which can be more efficient and flexible for numerical computations.


(365,)

### Q: Count the no. of days with rainfall between 0.5 and 1 inch using a NumPy array of rainfall in inches

In [214]:
np.sum((inches>0.5)&(inches<1))

29

### Q: Obtain the first 12 values in the following 3x4 matrix

In [217]:
arr2 = np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]]) #THE QUESTION WAS TO MAKE A MATRICE USING RAINFALL
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [218]:
matrix = inches[:12].reshape(3,4) # THE ANSWER
matrix
# Slicing the array: inches[:12] (you are selecting the first 12 elements from the inches array (from index 0 to index 11).)
# Reshaping the sliced array: .reshape(3, 4) ()

array([[0.        , 0.16141732, 0.05905512, 0.        ],
       [0.        , 0.01181102, 0.48031496, 0.38188976],
       [0.22834646, 0.16929134, 0.83858268, 0.05905512]])

### Q: Make the matrix after indexing (like 3rd to the 12th)___________________________[Check it]

In [220]:
matrix = inches[2:11].reshape(3,3)
matrix

array([[0.05905512, 0.        , 0.        ],
       [0.01181102, 0.48031496, 0.38188976],
       [0.22834646, 0.16929134, 0.83858268]])

### Q:How do we know whether a day was raining or not

In [222]:
rainy = np.sum(inches>0) # No. of rainy days
rainy

150

In [223]:
no_rain = np.sum(inches==0) # No. of days with no rain
no_rain 

215

In [224]:
np.shape(inches) # Is there a way to build a model using this data to predict whether there would be rain or not ? (there are 365 rows of data)

(365,)

### Q:How do we define summer days?


In [226]:
#First you should kn when is summer.
#Construct a mask of all summer days (june 21st is the 170th day, included and september 23rd is the 266nd day, excluded)

In [227]:
days = np.arange(365) #Not complete you gotta do this

### Q:Do basic statistics on rainy days, days without rain and summer days

In [237]:
# Mean, Median, Max, Min 

In [239]:
np.max(no_rain)

215